### ISSUE TITLE
Routing issue on /dashboard

### ISSUE THREAD

**Issue by bitcoinbrisbane** [horse-link/horse.link#18]
Should not break on when navigating to https://horse-link-puf2d.ondigitalocean.app/dashboard

## Steps to reproduce
- Navigate to https://horse-link-puf2d.ondigitalocean.app
- Refresh the page

## Expected behaviour
- Page should load

**Comment by ArshErgon** [comment]
its gives 404 in every URL, if I do a reload, (https://horse.link/dashboard)

**Comment by bitcoinbrisbane** [comment]
> its gives 404 in every URL, if I do a reload, (https://horse.link/dashboard), but why?

Yep, thats why i added as a bug!  Good that you can replicate it though.

**Comment by HritikR** [comment]
Maybe `HashRouter ` can solve this problem  Or  redirecting all requests `/*` to `/`

**Comment by HritikR** [comment]
> its gives 404 in every URL, if I do a reload, (https://horse.link/dashboard), but why?

@ArshErgon React Router provides client-side routing. Whenever you refresh the page or directly access the URL it will send the request to the server but that would give 404 errors because the server cannot find any document / static page in webroot.

Those same URLs work fine on the client-side, because there React Router is doing the routing for you, but they fail on the server-side unless you make your server understand them.

**Comment by pondpiu** [comment]
#36 address this by replacing `BrowserRouter` with `HashRouter`
Note that this is a quick fix 
the recommend way by CRA team can be seen here
`https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing`
